name: Kubernetes Deployment
on:
  push:
    branches:
      - main  # Trigger only on pushes to the main branch (adjust as needed)

jobs:
  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest

    steps:
      - name: Set up Kubernetes config
        env:
          KUBECONFIG: ${{ secrets.MYKUBECONFIG }}
        run: |
          mkdir -p ${HOME}/.kube
          echo "${{ secrets.MYKUBECONFIG }}" | base64 --decode > ${HOME}/.kube/config

      - name: Deploy to Kubernetes
        run: kubectl create deployment githubaction --image=docker.io/httpd
